spring.application.name=orderhub

spring.datasource.url=jdbc:mysql://localhost:3308/orderhub
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#when we mention it as validate when we create entitiy classes here and if it is missing a field when compared to actual db table. When we run the code hybernate will raise a issue.
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.open-in-view=false

#This creates or update the tables or columns in a db when we run the code (it executes the script that we have mentioned in db.migration, Once if a code is run it is not run again)
spring.flyway.enabled=true